### PR TITLE
Adds support for Svelte 4

### PR DESCRIPTION
**Pull request by VaelVictus**
Fully tested myself.

### CODE REVIEW

**Comment by VaelVictus** [comment]
Since the package is seemingly no longer maintained, I've taken up the mantle. 

https://www.npmjs.com/package/@vaelvictus/easyroute

**Comment by lyohaplotinka** [comment]
Hi @VaelVictus! 
Sorry for the long answer. Of course, I'll merge it.

**Comment by VaelVictus** [comment]
Thanks @lyohaplotinka, when can we expect it on npm?

**Comment by VaelVictus** [comment]
@lyohaplotinka Could you publish this update on npm? This package, alone, is holding me up from progressing with another task that I need done. I tried to fork it but couldn't figure out how to resolve some issues.

**Comment by lyohaplotinka** [comment]
@VaelVictus, done 👌

**Pull request merged**
